# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chipsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.CharField(max_length=16)),
                ('family', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amend.Chipsets')),
            ],
        ),
    ]
