# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipsets',
            name='name',
            field=models.CharField(default='CORRECTION NEEDED', max_length=32),
        ),
        migrations.AddField(
            model_name='softwareproducts',
            name='cs_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='softwareproducts',
            name='fc_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='softwareproducts',
            name='sod_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chipsets',
            name='chip',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chipsets',
            name='family',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='softwareproducts',
            name='sp_name',
            field=models.CharField(max_length=64),
        ),
    ]
