# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:00
from __future__ import unicode_literals

import camera.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0002_auto_20160102_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsets',
            name='chip',
            field=camera.customfields.UpperCaseCharField(max_length=32),
        ),
    ]
