# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0003_auto_20160102_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chipsets',
            new_name='Chipset',
        ),
        migrations.RenameModel(
            old_name='SoftwareProducts',
            new_name='SoftwareProduct',
        ),
    ]
