# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:15
from __future__ import unicode_literals

import camera.customfields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0004_auto_20160102_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipset',
            name='chip',
            field=camera.customfields.CustomCaseCharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chipset',
            name='family',
            field=camera.customfields.CustomCaseCharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='chipset',
            name='name',
            field=camera.customfields.CustomCaseCharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='cs_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='CS'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='fc_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='FC'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='sod_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='SOD'),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='sp_name',
            field=camera.customfields.CustomCaseCharField(max_length=64, verbose_name='SP Name'),
        ),
    ]
