# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:40
from __future__ import unicode_literals

import camera.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0005_auto_20160104_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipset',
            name='chip',
            field=camera.customfields.CustomCaseCharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='sp_name',
            field=camera.customfields.CustomCaseCharField(max_length=64, unique=True, verbose_name='SP Name'),
        ),
    ]
