# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:17
from __future__ import unicode_literals

import camera.customfields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0006_auto_20160104_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', camera.customfields.CustomCaseCharField(max_length=64, unique=True, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', camera.customfields.CustomCaseCharField(max_length=64, unique=True, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subarea', camera.customfields.CustomCaseCharField(max_length=64, unique=True, verbose_name='Sub Area')),
                ('feature_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subarea_fa', to='amend.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_trend', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fc_trend', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cs_trend', django.contrib.postgres.fields.jsonb.JSONField()),
                ('feature_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_fa', to='amend.Area')),
            ],
        ),
        migrations.AlterField(
            model_name='softwareproduct',
            name='chipset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sp_chip', to='amend.Chipset'),
        ),
        migrations.AddField(
            model_name='trend',
            name='sp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trend_sp', to='amend.SoftwareProduct'),
        ),
    ]
