# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 20:19
from __future__ import unicode_literals

import camera.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0007_auto_20160203_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseCount',
        ),
        migrations.AlterField(
            model_name='subarea',
            name='subarea',
            field=camera.customfields.CustomCaseCharField(max_length=64, verbose_name='Sub Area'),
        ),
    ]
