# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 20:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0008_auto_20160206_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), size=None)),
                ('featurearea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_fa', to='amend.Area')),
                ('softpro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_sp', to='amend.SoftwareProduct')),
            ],
        ),
    ]
