# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 18:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0010_auto_20160208_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('featurearea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_fa', to='amend.Area')),
                ('softpro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_sp', to='amend.SoftwareProduct')),
            ],
        ),
    ]
