# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0011_casecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecount',
            name='featurearea',
        ),
        migrations.RemoveField(
            model_name='casecount',
            name='softpro',
        ),
        migrations.DeleteModel(
            name='CaseCount',
        ),
    ]
