# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0012_auto_20160209_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(0, b'L0'), (1, b'L1'), (2, b'L2'), (3, b'L3'), (4, b'L4')], max_length=200)),
                ('count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_geo', to='amend.Geo')),
                ('softpro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_sp', to='amend.SoftwareProduct')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_subarea', to='amend.SubArea')),
            ],
        ),
    ]
