# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amend', '0013_casecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovPassPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(0, b'L0'), (1, b'L1'), (2, b'L2'), (3, b'L3'), (4, b'L4')], max_length=3)),
                ('tottc', models.IntegerField()),
                ('covtc', models.IntegerField()),
                ('passtc', models.IntegerField()),
                ('failtc', models.IntegerField()),
                ('blocktc', models.IntegerField()),
                ('na_nr_tc', models.IntegerField()),
                ('covper', models.IntegerField()),
                ('passper', models.IntegerField()),
                ('failper', models.IntegerField()),
                ('blockper', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp_geo', to='amend.Geo')),
                ('softpro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp_sp', to='amend.SoftwareProduct')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp_subarea', to='amend.SubArea')),
            ],
        ),
        migrations.AlterField(
            model_name='casecount',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='casecount',
            name='level',
            field=models.CharField(choices=[(0, b'L0'), (1, b'L1'), (2, b'L2'), (3, b'L3'), (4, b'L4')], max_length=3, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='casecount',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_geo', to='amend.Geo', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='casecount',
            name='softpro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_sp', to='amend.SoftwareProduct', verbose_name='SP'),
        ),
        migrations.AlterField(
            model_name='casecount',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_subarea', to='amend.SubArea', verbose_name='Area-SubArea'),
        ),
    ]
